
---
- name: "Update chown to {{ user }}:{{ remote_server_user }}"
  file:
    path: "{{ ansistrano_deploy_to }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ remote_server_user }}"
    mode: 0775
    recurse: yes

- name: "Change bootstrap cache folder permission and ownner"
  file:
    path: "{{ ansistrano_release_path.stdout }}/bootstrap/cache"
    state: directory
    owner: "{{ user }}"
    group: "{{ remote_server_user }}"
    mode: 0775
    follow: yes
    recurse: yes

- name: "Change storage folder permission and ownner"
  file:
    path: "{{ ansistrano_shared_path }}/storage"
    state: directory
    mode: 0775
    owner: "{{ user }}"
    group: "{{ remote_server_user }}"
    follow: yes
    recurse: yes


