---
- name: Add crontab entry for Laravel scheduler
  become: "{{ user }}"
  cron:
      name: "Run Laravel scheduler"
      job: "php {{ deploy_path }}/current/artisan schedule:run --quiet"
      state: present
  when: scheduler == 'yes' or scheduler == 'true'
