---
- name: Import database from host to remote
  hosts: all
  gather_facts: no
  remote_user:  "{{ user }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_winrm_server_cert_validation: ignore
    database_dump_filename: dump
    current_realease_path:  "/home/{{ user }}/{{ domain }}/current"
    database_dump_folder: "database/snapshots/{{ database_dump_filename }}.sql"
  tasks:

  - name: Include variables
    include_vars: "{{ playbooks_directory_path }}/variables/vars.yml"

  - name: Include password file
    include_vars: "{{ temporary_dir }}/variables/passwords.yml"

  - name: Dump remote database
    become: "{{ remote_default_user }}"
    shell: "php artisan snapshot:create {{ database_dump_filename }}"
    args:
      chdir: "{{ temporary_dir | dirname }}"
    delegate_to: localhost

  - name: Create database snapshots folder
    file:
      path: "{{ current_realease_path }}/{{ database_dump_folder }}"
      state: directory

  - name: Copy file from host to remote
    become: "{{ remote_default_user }}"
    copy:
      src: "{{ temporary_dir | dirname }}/{{ database_dump_folder }}"
      dest: "{{ current_realease_path }}/{{ database_dump_folder }}"

  - name: Import host database in remote
    command: "php artisan snapshot:load {{ database_dump_filename }} --force"
    args:
      chdir: "{{ current_realease_path }}"

  - name: Remove remote dump file
    shell: "php artisan snapshot:delete {{ database_dump_filename }}"
    args:
      chdir: "{{ current_realease_path }}"

  - name: Remove host dump file
    command: "php artisan snapshot:delete {{ database_dump_filename }}"
    args:
      chdir: "{{ temporary_dir | dirname }}"
    delegate_to: localhost

  - name: Change admin password
    command: "php artisan administrable:guard:update --field=password --value={{ vault_admin_production_password }} --id=1"
    args:
      chdir: "{{ current_realease_path }}"

  - name: Clear database cache
    command: "php artisan modelCache:clear"
    args:
      chdir: "{{ current_realease_path }}"

