---
- name: Import database from remote to host
  hosts: all
  gather_facts: no
  remote_user:  "{{ user }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_winrm_server_cert_validation: ignore
    database_dump_filename: dump
    current_realease_path:  "/home/{{ user }}/{{ domain }}/current"
    database_dump_folder: "database/snapshots/{{ database_dump_filename }}.sql"
  tasks:

  - name: Include variables
    include_vars: "{{ playbooks_directory_path }}/variables/vars.yml"

  - name: Include password file
    include_vars: "{{ temporary_dir }}/variables/passwords.yml"

  - name: Dump remote database
    shell: "php artisan snapshot:create {{ database_dump_filename }}"
    args:
      chdir: "{{ current_realease_path }}"

  - name: Copy file from remote to host
    fetch:
      src: "{{ current_realease_path }}/{{ database_dump_folder }}"
      dest: "{{ temporary_dir | dirname }}/{{ database_dump_folder }}"
      flat: yes

  - name: Import remote database in host
    command: "php artisan snapshot:load {{ database_dump_filename }}"
    become: "{{ remote_default_user }}"
    args:
      chdir: "{{ temporary_dir | dirname }}"
    delegate_to: localhost

  - name: Remove remote dump file
    shell: "php artisan snapshot:delete {{ database_dump_filename }}"
    args:
      chdir: "{{ current_realease_path }}"

  - name: Remove host dump file
    command: "php artisan snapshot:delete {{ database_dump_filename }}"
    become: "{{ remote_default_user }}"
    args:
      chdir: "{{ temporary_dir | dirname }}"
    delegate_to: localhost

  - name: Change admin password
    command: "php artisan administrable:guard:update --field=password --value={{ vault_admin_local_password }} --id=1"
    args:
      chdir: "{{ temporary_dir | dirname }}"
    delegate_to: localhost
