---
- name: Import storage folder from remote to host
  hosts: all
  gather_facts: no
  remote_user:  "{{ user }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_winrm_server_cert_validation: ignore
    dump_path: "{{ current_realease_path }}/{{ application }}storage.zip"
    storage_dump_folder: "{{ current_realease_path }}/storage/app/public"
    local_storage_folder: "{{ playbooks_directory_path | dirname }}/storage/app/public"

  tasks:
  - name: Include variables
    include_vars: "{{ playbooks_directory_path }}/variables/vars.yml"

  - name: Zip storage folder
    archive:
      path: "{{ storage_dump_folder }}"
      dest: "{{ dump_path }}"
      format: zip

  - name: Copy file from remote to host
    fetch:
      src: "{{ dump_path }}"
      dest: "{{ storage_dump_path }}/"
      flat: yes

  - name: Empty local storage folder
    become_user: "{{ remote_default_user }}"
    file:
      state: absent
      path: "{{ local_storage_folder }}"
    delegate_to: localhost

  - name: Create local storage folder
    become_user: "{{ remote_default_user }}"
    file:
      state: directory
      path: "{{ local_storage_folder }}"
    delegate_to: localhost

  - name: Extract files
    become_user: "{{ remote_default_user }}"
    unarchive:
      copy: no
      src: "{{ storage_dump_path }}/{{ application }}storage.zip"
      dest: "{{ playbooks_directory_path | dirname }}/storage/app/"
    delegate_to: localhost

  - name: Ensure correct folder ownership
    file:
      path: "{{ local_storage_folder }}"
      state: directory
      owner: "{{ remote_default_user }}"
      group: "{{ remote_default_user }}"
      recurse: yes
    delegate_to: localhost

  - name: Delete remote archive
    file:
      path: "{{ dump_path }}"
      state: absent

  - name: Delete host archive
    file:
      path: "{{ storage_dump_path }}/{{ application }}storage.zip"
      state: absent
    delegate_to: localhost
