#  Rollback laravel project
---
- name: Rollback laravel project
  hosts: all
  gather_facts: no
  become: yes
  remote_user: "{{ user }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: Include variables
      include_vars: "{{ playbooks_directory_path }}/variables/vars.yml"

    - name: Include password file
      include_vars: "{{ playbooks_directory_path }}/variables/passwords.yml"

    - include_role:
        name: ansistrano.rollback
